# fly.toml app configuration file generated for irenciodapaz-fincances-api on 2024-12-20T15:25:28Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'irenciodapaz-fincances-api'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256m'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
